/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PruebaInterfaz;
import PruebaLista.ListaDoblePaciente;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import prueba1.NodoPaciente;
import prueba1.Paciente;

/**
 *
 * @author Jean
 */
public class JpPacientes extends javax.swing.JPanel {
    private ListaDoblePaciente listaPacientes;
    /**
     * Creates new form Pacientes
     */
    public JpPacientes() {
        initComponents();
        listaPacientes = new ListaDoblePaciente();
        listar();
    }
    
    private void listar() {
        jTable1.setModel(listaPacientes.imprimirIDPaciente());
    }

    private void limpiarCajas() {
        txtDni.setText("");
        txtPacNombres.setText("");
        txtPacApellidos.setText("");
        txtPacFechaNac.setText("");
        txtPacCelular.setText("");
        txtPacSeguro.setText("");
        txtDni.requestFocus();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnPacInsertar = new javax.swing.JButton();
        btnPacModificar = new javax.swing.JButton();
        btnPacEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtDni = new javax.swing.JTextField();
        txtPacNombres = new javax.swing.JTextField();
        txtPacApellidos = new javax.swing.JTextField();
        txtPacCelular = new javax.swing.JTextField();
        txtPacSeguro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPacFechaNac = new javax.swing.JFormattedTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        btnPacInsertar.setText("Insertar");
        btnPacInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacInsertarActionPerformed(evt);
            }
        });

        btnPacModificar.setText("Modificar");
        btnPacModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacModificarActionPerformed(evt);
            }
        });

        btnPacEliminar.setText("Eliminar");
        btnPacEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacEliminarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });

        txtPacApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacApellidosActionPerformed(evt);
            }
        });

        txtPacSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacSeguroActionPerformed(evt);
            }
        });

        jLabel1.setText("DNI");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Fecha Nacimiento");

        jLabel5.setText("Numero Celular");

        jLabel6.setText("Seguro");

        try {
            txtPacFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("**/**/****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(txtPacNombres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPacApellidos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPacCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtPacSeguro)
                    .addComponent(txtPacFechaNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPacModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPacInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPacEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPacInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPacModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPacEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPacNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPacApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPacFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPacCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPacSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPacSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacSeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacSeguroActionPerformed

    private void txtPacApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacApellidosActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_txtPacApellidosActionPerformed

    private void btnPacInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacInsertarActionPerformed
        try {
            String dni = txtDni.getText().trim();
            String nombres = txtPacNombres.getText().trim();
            String apellidos = txtPacApellidos.getText().trim();
            String celular = txtPacCelular.getText().trim();
            String seguro = txtPacSeguro.getText().trim();

            if (dni.isEmpty() || nombres.isEmpty() || apellidos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor complete los datos principales (DNI, Nombres, Apellidos)");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date fecha = sdf.parse(txtPacFechaNac.getText().trim());

            Paciente nuevoPaciente = new Paciente(dni, nombres, apellidos, fecha, celular, seguro);
            listaPacientes.insertar(nuevoPaciente);

            listar(); 
            limpiarCajas();
            JOptionPane.showMessageDialog(this, "Paciente registrado con exito");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: Verifique el formato de la fecha (dd/mm/aaaa)");
        }
    }//GEN-LAST:event_btnPacInsertarActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDniActionPerformed

    private void btnPacModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacModificarActionPerformed
        try {
            String dni = txtDni.getText().trim();
            String nombres = txtPacNombres.getText().trim();
            String apellidos = txtPacApellidos.getText().trim();
            String celular = txtPacCelular.getText().trim();
            String seguro = txtPacSeguro.getText().trim();

            if (dni.isEmpty() || nombres.isEmpty() || apellidos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor complete los datos principales (DNI, Nombres, Apellidos)");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date fecha = sdf.parse(txtPacFechaNac.getText().trim());

            Paciente nuevoPaciente = new Paciente(dni, nombres, apellidos, fecha, celular, seguro);
            listaPacientes.insertar(nuevoPaciente);

            listar(); 
            limpiarCajas();
            JOptionPane.showMessageDialog(this, "Paciente registrado con exito");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: Verifique el formato de la fecha (dd/mm/aaaa)");
        }
    }//GEN-LAST:event_btnPacModificarActionPerformed

    private void btnPacEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacEliminarActionPerformed
        String dni = txtDni.getText().trim();
        if (dni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un paciente de la tabla o ingrese un DNI para eliminar");
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(this, "Esta seguro de eliminar al paciente con DNI " + dni + "?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            listaPacientes.eliminarID(dni);
            listar(); 
            limpiarCajas();
            JOptionPane.showMessageDialog(this, "Paciente removido del sistema");
        }
    }//GEN-LAST:event_btnPacEliminarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
            String dni = jTable1.getValueAt(filaSeleccionada, 0).toString();
            NodoPaciente nodo = listaPacientes.buscar(dni);

            if (nodo != null) {
                Paciente p = nodo.getDato();
                txtDni.setText(p.getDni());
                txtPacNombres.setText(p.getNombres());
                txtPacApellidos.setText(p.getApellidos());

                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                txtPacFechaNac.setText(p.getFechaNacimiento() != null ? sdf.format(p.getFechaNacimiento()) : "");
                txtPacCelular.setText(p.getCelular());
                txtPacSeguro.setText(p.getSeguro()); // Corregido a txtPacSeguro segun tus variables del final
            }
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPacEliminar;
    private javax.swing.JButton btnPacInsertar;
    private javax.swing.JButton btnPacModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtPacApellidos;
    private javax.swing.JTextField txtPacCelular;
    private javax.swing.JFormattedTextField txtPacFechaNac;
    private javax.swing.JTextField txtPacNombres;
    private javax.swing.JTextField txtPacSeguro;
    // End of variables declaration//GEN-END:variables
}
